### ISSUE TITLE
Doesn't install on classic BG2/linux

### ISSUE THREAD

**Issue by burner1024** [SpellholdStudios/RuadRofhessaItemUpgrade#1]
Probably windows too, but I don't have it to check.
```
Install Component [Ruad Ro'fhessa (SoA)]?
[I]nstall, or [N]ot Install or [Q]uit? 
Installing [Ruad Ro'fhessa (SoA)] [v29.0.0]
ERROR: cannot convert is_1pp_helmet or %is_1pp_helmet% to an integer
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Ruad Ro'fhessa (SoA)], rolling back to previous state
```

**Comment by GwendolyneFreddy** [comment]
Which version are you installing?
I reinstalled it a few minutes ago and every thing worked fine.

**Comment by burner1024** [comment]
v29.0.0

**Comment by GwendolyneFreddy** [comment]
Try with the latest one, because afair there was a beta 29.0.0 before...

If it still does not work with the latest version, open always.tpa file (in /lib folder), then replace line #62

ACTION_IF (is_ee OR is_1pp_staff OR is_1pp_staff0 OR is_1pp_helmet OR is_1pp_400 OR is_1pp_401 OR is_1pp_swblbw) BEGIN

with

ACTION_IF (is_ee OR is_1pp_staff OR is_1pp_staff0 OR is_1pp_400 OR is_1pp_401 OR is_1pp_swblbw) BEGIN

And try to install.
Let me know if it solves the issue.

**Comment by burner1024** [comment]
installs with the change

**Comment by GwendolyneFreddy** [comment]
I really don't understand why linux OS fails with this code which works fine with W10...

Anyway, I will fix it and upload a silent release this evening.

Thanks for reporting!

**Comment by burner1024** [comment]
I don't think it's linux, rather than a missing var. Are you testing on EE?

**Comment by GwendolyneFreddy** [comment]
I update those mods for classic games, then write EE compatibility.
I installed it both on classic ToB, BGT and BG2:EE without any issue.

1pp_helmet variable was used during the updating process, but I eventually got rid of it.

**Comment by burner1024** [comment]
I have tried the release with wine, still fails. It's not the linux, something's off in your testing process.

**Comment by GwendolyneFreddy** [comment]
New release : https://github.com/SpellholdStudios/RuadRofhessaItemUpgrade/releases

**Comment by burner1024** [comment]
That one works, thanks!
